name: 01 - Intro aux actions

on:
  workflow_dispatch:

jobs:
  restore_project:
    name: Checkout
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: List files
        run: ls -la
